# Generated by Django 3.0.3 on 2024-04-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('username', models.CharField(default='', max_length=255, verbose_name='用户名')),
                ('password', models.CharField(default='', max_length=255, verbose_name='密码')),
                ('email', models.CharField(default='', max_length=255, verbose_name='邮箱')),
                ('phone', models.CharField(default='', max_length=255, verbose_name='电话')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '普通用户',
                'verbose_name_plural': '普通用户',
                'db_table': 'user',
            },
        ),
    ]
