# Generated by Django 3.0.3 on 2024-04-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20240422_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisherman',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='fisherman',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='fisherman',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='fisherman',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='电话'),
        ),
    ]
